# Generated by Django 4.2.6 on 2023-10-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0018_alter_candidate_location'),
        ('jobs', '0021_jobsubmissionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('candidates', models.ManyToManyField(blank=True, to='candidates.candidate')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='jobs.job')),
            ],
        ),
    ]
