# Generated by Django 4.2.5 on 2023-09-08 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_location_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('Onsite', 'Onsite')], max_length=20)),
                ('job_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Hold', 'Hold'), ('Upcoming', 'Upcoming')], default='Open', max_length=20)),
                ('job_work_hours', models.TextField()),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract'), ('Contract to Hire', 'Contract to Hire')], max_length=20)),
                ('job_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('job_attachment', models.FileField(blank=True, null=True, upload_to='job_attachments/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
