# Generated by Django 4.2.5 on 2023-09-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_location_type',
            new_name='job_mode',
        ),
    ]
