# Generated by Django 4.2.5 on 2023-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'FT'), ('Cont', 'Con'), ('C2H', 'C2H')], max_length=20),
        ),
    ]
