# Generated by Django 4.2.5 on 2023-09-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_delete_candidategoestojob'),
        ('jobs', '0007_alter_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='candidates',
            field=models.ManyToManyField(through='jobs.JobSubmission', to='candidates.candidate'),
        ),
    ]
