# Generated by Django 4.2.5 on 2023-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobsubmission_job_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='date_status_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='submission_status',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Client', 'Client'), ('QC Reject', 'QC Reject'), ('L1 Interview', 'L1 Interview'), ('L2 Interview', 'L2 Interview'), ('L3 Interview', 'L3 Interview'), ('Shortlisted', 'Shortlisted'), ('Joined', 'Joined')], default='Internal', max_length=20),
        ),
    ]
