# Generated by Django 4.2.5 on 2023-09-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobsubmission_date_status_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubmission',
            old_name='date_status_updated',
            new_name='date_stage_updated',
        ),
        migrations.RemoveField(
            model_name='jobsubmission',
            name='submission_status',
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='stage',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Manager Review', 'Manager Review'), ('Client Submission', 'Client Submission'), ('QC Reject', 'QC Reject'), ('L1 Interview', 'L1 Interview'), ('L2 Interview', 'L2 Interview'), ('L3 Interview', 'L3 Interview'), ('Shortlisted', 'Shortlisted'), ('Joined', 'Joined')], default='Internal', max_length=20),
        ),
    ]
