# Generated by Django 4.2.5 on 2023-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_date_status_updated_jobsubmission_date_stage_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='stage',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Client Submission', 'Client Submission'), ('QC Reject', 'QC Reject'), ('L1 Interview', 'L1 Interview'), ('L2 Interview', 'L2 Interview'), ('L3 Interview', 'L3 Interview'), ('Interview Reject', 'Interview Reject'), ('Shortlisted', 'Shortlisted'), ('Joined', 'Joined')], default='Internal', max_length=20),
        ),
    ]
