# Generated by Django 4.2.5 on 2023-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobsubmission_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='stage_changed_date',
            field=models.DateField(auto_now=True),
        ),
    ]
