# Generated by Django 4.2.5 on 2023-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobsubmission_stage_changed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmission',
            name='date_stage_updated',
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='stage_changed_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
