# Generated by Django 4.2.5 on 2023-09-10 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_jobsubmission_date_stage_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='stage_changed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
