# Generated by Django 4.2.5 on 2023-09-13 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_jobsubmission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='stage_changed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
