# Generated by Django 4.2.5 on 2023-09-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_jobsubmission_stage_changed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='previous_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
