# Generated by Django 4.2.5 on 2023-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_jobsubmission_client_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubmission',
            old_name='client_submission_date',
            new_name='date_client_submitted',
        ),
    ]
