# Generated by Django 4.2.5 on 2023-09-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_rename_client_submission_date_jobsubmission_date_client_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmission',
            name='feedback',
        ),
    ]
