# Generated by Django 4.2.6 on 2023-10-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_jobsubmission_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField()),
                ('job_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='jobs.jobsubmission')),
            ],
        ),
    ]
