# Generated by Django 4.2.6 on 2023-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_jobsubmissionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_minimum_experience',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
