# Generated by Django 4.2.6 on 2023-10-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
