# Generated by Django 4.2.6 on 2023-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_remove_job_skills_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_notes',
            field=models.TextField(default='Dummy Notes'),
            preserve_default=False,
        ),
    ]
