# Generated by Django 4.2.5 on 2023-09-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default='code', max_length=200),
            preserve_default=False,
        ),
    ]
