# Generated by Django 4.2.5 on 2023-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_hq_client_office_alter_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hq',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
