# Generated by Django 4.2.6 on 2023-10-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailclient', '0002_gmailaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmailAccount',
        ),
    ]
