# Generated by Django 4.2.6 on 2023-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailclient', '0004_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
