# Generated by Django 4.2.5 on 2023-09-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('cv', models.FileField(upload_to='CV_All/')),
                ('current_ctc', models.DecimalField(decimal_places=0, max_digits=10)),
                ('expected_ctc', models.DecimalField(decimal_places=0, max_digits=10)),
                ('notice_period', models.PositiveIntegerField(help_text='In days')),
                ('serving_notice_period', models.BooleanField(default=False)),
                ('last_working_day', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_joining_date', models.CharField(blank=True, max_length=200, null=True)),
                ('total_experience', models.PositiveIntegerField(help_text='In years')),
                ('relevant_experience', models.PositiveIntegerField(help_text='In years')),
                ('reason_for_change', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.CharField(blank=True, max_length=200)),
                ('recruiter_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobs', models.ManyToManyField(related_name='candidates_submitted', to='jobs.job')),
            ],
        ),
    ]
