# Generated by Django 4.2.5 on 2023-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.EmailField(default='Delhi', max_length=200),
            preserve_default=False,
        ),
    ]
