# Generated by Django 4.2.5 on 2023-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='jobs',
        ),
    ]
