# Generated by Django 4.2.5 on 2023-09-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidategoestojob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateGoesToJob',
        ),
    ]
