# Generated by Django 4.2.5 on 2023-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_delete_candidategoestojob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notice_period',
            field=models.PositiveIntegerField(blank=True, help_text='In days', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='reason_for_change',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recruiter_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='relevant_experience',
            field=models.PositiveIntegerField(blank=True, help_text='In years', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='serving_notice_period',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='total_experience',
            field=models.PositiveIntegerField(blank=True, help_text='In years', null=True),
        ),
    ]
