# Generated by Django 4.2.5 on 2023-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_alter_candidate_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
