# Generated by Django 4.2.6 on 2023-10-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('recruiter', 'Sourced'), ('application', 'Incoming')], default='recruiter', max_length=20),
        ),
    ]
