# Generated by Django 4.2.6 on 2023-10-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_alter_candidate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
