# Generated by Django 4.2.6 on 2023-10-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='category',
        ),
        migrations.DeleteModel(
            name='EmailCategory',
        ),
    ]
