# Generated by Django 4.2.6 on 2023-10-26 13:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_emailtemplate_category_delete_emailcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsignature',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='emailsignature',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
