# Generated by Django 4.2.6 on 2023-10-27 07:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_emailsignature_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
