# Generated by Django 4.2.6 on 2023-10-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_object_id_charfield'),
        ('settings', '0004_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAttachment',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachments.attachment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.emailtemplate')),
            ],
            bases=('attachments.attachment',),
        ),
    ]
