# Generated by Django 4.2.5 on 2023-09-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0017_jobsubmission_previous_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Face-to-Face', 'Face-to-Face'), ('Telephone', 'Telephone')], max_length=20, null=True)),
                ('interviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback', models.CharField(default='Pending', max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
