# Generated by Django 4.2.5 on 2023-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interview_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='stage',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Client Submission', 'Client Submission'), ('QC Reject', 'QC Reject'), ('L1 Interview', 'L1 Interview'), ('L2 Interview', 'L2 Interview'), ('L3 Interview', 'L3 Interview'), ('Interview Reject', 'Interview Reject'), ('Shortlisted', 'Shortlisted'), ('Joined', 'Joined')], default='pe', max_length=20),
            preserve_default=False,
        ),
    ]
