# Generated by Django 4.2.5 on 2023-09-19 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interview_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('changed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview')),
            ],
        ),
    ]
